# Site wide configuration

title: Nuit Debout Epinal
description: le site de Nuit Debout Epinal
logo: logoEpinal.jpg# 120x120 px default image used for Twitter summary card
teaser: teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: fr
# url: http://www.nuitdeboutepinal.fr


# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
# permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
# post_layout: article
# page_layout: article

# Format titles with titlecase?
titlecase: true


include:
  - _pages

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]


collections:
  commissions:
    output: true
    permalink: /:collection/:path/
    title: Commissions
  faqs:
    output: true
    permalink: /:collection/:path/
    title: Foire Aux Questions


prose:
  siteurl: 'http://www.nuitdeboutepinal.fr/'
  rooturl: '_posts'
  media: 'images'
  ignore: [ "atom.xml", "/_includes", "_config.yml", "/_layouts"]
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Titre"
      - name: "date"
        field:
          element: "text"
          label: "Date de publication"
          value: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "select"
          label: "Catégorie"
          placeholder: "Choisissez une categorie"
          options:
            - name: "Animation"
              value: "animation"
            - name: "Action"
              value: "action"
            - name: "Antipub"
              value: "antipub"
            - name: "Cuisine"
              value: "cuisine"
            - name: "Documentation"
              value: "documentation"
            - name: "Entrepreneuriat Social"
              value: "entrepreneuriatsocial"
            - name: "Environnement"
              value: "environnement"
            - name: "Jardin"
              value: "jardin"
            - name: "Logistique"
              value: "logistique"
            - name: "Media"
              value: "media"
            - name: "Projection"
              value: "projection"
            - name: "Projet de société"
              value: "projetdesociete"
     _commissions:
      - name: "layout"
        field:
          element: "hidden"
          value: "commission"
      - name: "symbol"
        field:
          element: "select"
          label: "Mot clé"
          placeholder: "Choisissez le mot-clé"
          options:
            - name: "Animation"
              value: "animation"
            - name: "Action"
              value: "action"
            - name: "Antipub"
              value: "antipub"
            - name: "Cuisine"
              value: "cuisine"
            - name: "Documentation"
              value: "documentation"
            - name: "Entrepreneuriat Social"
              value: "entrepreneuriatsocial"
            - name: "Environnement"
              value: "environnement"
            - name: "Jardin"
              value: "jardin"
            - name: "Logistique"
              value: "logistique"
            - name: "Media"
              value: "media"
            - name: "Projection"
              value: "projection"
            - name: "Projet de société"
              value: "projetdesociete"
    _faqs:
      - name: "layout"
        field:
          element: "hidden"
          value: "faq"
      - name: "position"
        field:
          element: "number"
          help: "Détermine l'ordre d'affichage de la question sur la page (comparer aux positions des autres questions !)"
          type: number
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          element: "button"
          label: "Statut"
          help: "Si publié, la question est visible"
          on: "Publié"
          off: "Caché"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""