# Site wide configuration

title: Nuit Debout Epinal
description: le site de Nuit Debout Epinal
logo: logoEpinal.jpg# 120x120 px default image used for Twitter summary card
teaser: teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: fr
# url: http://www.nuitdeboutepinal.fr


# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
# permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
# post_layout: article
# page_layout: article

# Format titles with titlecase?
titlecase: true


include:
  - _pages

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]


collections:
  commissions:
    output: true
    permalink: /:collection/:path/
    title: Commissions
  faqs:
    output: true
    permalink: /:collection/:path/
    title: Foire Aux Questions


prose:
  siteurl: 'http://www.nuitdeboutepinal.fr/'
  rooturl: '_posts'
  media: 'images'
  ignore: [ "atom.xml", "/_includes", "_config.yml", "/_layouts"]
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Titre"